# Generated by Django 2.0 on 2018-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('instruction', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drink',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('steporder', models.IntegerField()),
                ('drink', models.IntegerField()),
                ('ingredient', models.IntegerField()),
                ('serving', models.IntegerField()),
                ('direction', models.IntegerField()),
            ],
            options={
                'db_table': 'recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measurement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'serving',
                'managed': False,
            },
        ),
    ]
